const CONFIG = {
  apiBase: window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "http://localhost:8000"
    : "https://node-notes-api-zaxk.onrender.com",
  vaultPrefix: "vault/",
  noteSuffix: ".md",
  deleteConfirmMs: 4000,
  draftBodyKey: "nn_draft_body",
  draftTitleKey: "nn_draft_title",
  draftFolderKey: "nn_draft_folder",
  folderHistoryKey: "nn_folder_history",
  lastFolderKey: "nn_last_folder",
};

const elements = {
  authStatusLoading: document.getElementById("auth-status-loading"),
  authStatusSignedIn: document.getElementById("auth-status-signed-in"),
  authStatusSignedOut: document.getElementById("auth-status-signed-out"),
  userAvatar: document.getElementById("user-avatar"),
  userLogin: document.getElementById("user-login"),
  loginBtn: document.getElementById("login-btn"),
  logoutBtn: document.getElementById("logout-btn"),
  folderInput: document.getElementById("note-folder"),
  privateModeToggle: document.getElementById("private-mode-toggle"),
  folderDatalist: document.getElementById("folder-suggestions"),
  folderHint: document.getElementById("folder-hint"),
  folderChips: document.getElementById("folder-chips"),
  titleInput: document.getElementById("note-title"),
  bodyInput: document.getElementById("note-body"),
  noteSearchInput: document.getElementById("note-search"),
  uploadBtn: document.getElementById("upload-btn"),
  cancelEditBtn: document.getElementById("cancel-edit-btn"),
  draftTag: document.getElementById("draft-tag"),
  statusBar: document.getElementById("status-bar"),
  statusText: document.getElementById("status-text"),
  noteList: document.getElementById("note-list"),
  noteCount: document.getElementById("note-count"),
  writeTab: document.getElementById("write-tab"),
  previewTab: document.getElementById("preview-tab"),
  writePane: document.getElementById("write-pane"),
  previewPane: document.getElementById("preview-pane"),
  previewTitle: document.getElementById("preview-title"),
  previewBody: document.getElementById("preview-body"),
};

const state = {
  mode: "create",
  editingPath: null,
  editingSha: null,
  draftSnapshot: null,
  notes: [],
  searchQuery: "",
  listStatus: "idle",
  listError: "",
  isMutating: false,
  confirmDeletePath: null,
  deleteConfirmTimer: null,
  titleLocked: false,
  autoGeneratedTitle: "",
  folderHistory: [],
  folderIndex: [],
  excludePatterns: [],
  privateMode: false,
  isAuthenticated: false,
  user: null,
};

import { setupEditor } from './editor/editor.js';
import { triggerFilePicker, triggerCameraCapture } from './editor/assets.js';

setupEditor(elements.bodyInput, () => state);

function escapeHtml(v) {
  return String(v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function normalizeFolderPath(path) {
  if (!path) return "";
  return path
    .replace(/\\/g, '/')
    .replace(/\/+/g, '/')
    .replace(/\s*\/\s*/g, '/')
    .replace(/^\/+|\/+$/g, '')
    .trim();
}

function isExcludedPath(path) {
  if (!path) return false;
  const parts = path.split("/");
  return parts.some(part => state.excludePatterns.includes(part));
}

let fuseIndex = null;

const mathExtension = {
  name: 'math',
  level: 'inline',
  start(src) {
    const m = src.match(/\$/);
    return m ? m.index : -1;
  },
  tokenizer(src, tokens) {
    const blockRule = /^\$\$(?:[\s\S]*?)\$\$/;
    const inlineRule = /^\$([^$\n]+?)\$/;
    let match;
    if ((match = blockRule.exec(src))) {
      return {
        type: 'math',
        raw: match[0],
        text: match[1],
        displayMode: true
      };
    } else if ((match = inlineRule.exec(src))) {
      return {
        type: 'math',
        raw: match[0],
        text: match[1],
        displayMode: false
      };
    }
  },
  renderer(token) {
    if (token.displayMode) return `\\[${escapeHtml(token.text)}\\]`;
    return `\\(${escapeHtml(token.text)}\\)`;
  }
};
if (typeof marked !== "undefined") {
  try {
    marked.use({ extensions: [mathExtension] });
  } catch {}
}

function updateFuseIndex() {
  if (typeof Fuse === "undefined") return;
  fuseIndex = new Fuse(state.notes, {
    keys: [
      { name: 'title', weight: 0.7 },
      { name: 'displayPath', weight: 0.3 }
    ],
    includeMatches: true,
    threshold: 0.4,
  });
}

function highlightMatch(text, matches, key) {
  const match = matches ? matches.find(m => m.key === key) : null;
  if (!match) return escapeHtml(text);
  
  let result = '', last = 0;
  for (const [start, end] of match.indices) {
    result += escapeHtml(text.slice(last, start));
    result += `<mark class="highlight-match">${escapeHtml(text.slice(start, end + 1))}</mark>`;
    last = end + 1;
  }
  return result + escapeHtml(text.slice(last));
}

function extractAutoTitle(body) {
  const match = body.match(/^#\s+(.*)$/m);
  if (match && match[1].trim()) {
    return match[1].trim().slice(0, 80).replace(/[\\/:*?"<>|]/g, "");
  }
  const lines = body.split('\n');
  for (const line of lines) {
    if (line.trim()) {
      return line.trim().slice(0, 80).replace(/[\\/:*?"<>|]/g, "");
    }
  }
  return "";
}

function setStatus(type, message) {
  elements.statusBar.className = `status visible ${type}`;
  elements.statusText.textContent = message;
}

function isVaultPathSafe(path, { isAsset = false } = {}) {
  const prefix = CONFIG.vaultPrefix;
  return typeof path === "string" 
    && path.startsWith(prefix) 
    && (isAsset || path.endsWith(CONFIG.noteSuffix)) 
    && !path.includes("..") 
    && !path.includes("\\");
}

function noteStemFromPath(path) {
  return path.split("/").pop().replace(/\.md$/i, "");
}

function buildFilename(title) {
  if (title.trim()) return `${title.trim().replace(/\.md$/i, "")}.md`;
  const pad = (n, l = 2) => String(n).padStart(l, '0');
  const d = new Date();
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}T${pad(d.getUTCHours())}-${pad(d.getUTCMinutes())}-${pad(d.getUTCSeconds())}-${pad(d.getUTCMilliseconds(), 3)}Z.md`;
}

function buildMarkdown(title, body, fallbackTitle) {
  const safeTitle = (title || fallbackTitle).replace(/"/g, "\\\"");
  return [
    "---",
    `title: "${safeTitle}"`,
    `date: ${new Date().toISOString()}`,
    "tags: [vault, web]",
    "---",
    "",
    body,
  ].join("\n");
}

function parseEditableNote(path, markdown) {
  const fallback = noteStemFromPath(path);
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) return { title: fallback, body: markdown };

  const titleMatch = match[1].match(/^title\s*:\s*(?:"((?:\\"|[^"])*)"|'([^']*)'|(.+))\s*$/m);
  const rawTitle = titleMatch ? (titleMatch[1] || titleMatch[2] || titleMatch[3] || "") : "";
  return {
    title: rawTitle.replace(/\\"/g, "\"").trim() || fallback,
    body: markdown.slice(match[0].length)
  };
}

function saveDraftSoon() {
  clearTimeout(saveDraftSoon.timerId);
  saveDraftSoon.timerId = setTimeout(() => {
    try {
      localStorage.setItem(CONFIG.draftBodyKey, elements.bodyInput.value);
      localStorage.setItem(CONFIG.draftTitleKey, elements.titleInput.value);
      const folderRaw = elements.folderInput.value;
      const folder = normalizeFolderPath(folderRaw);
      
      if (!isExcludedPath(folder) && !state.privateMode) {
        localStorage.setItem(CONFIG.draftFolderKey, folderRaw);
      } else {
        localStorage.removeItem(CONFIG.draftFolderKey);
      }
      
      elements.draftTag.classList.toggle(
        "visible",
        Boolean(elements.bodyInput.value || elements.titleInput.value || folderRaw),
      );
    } catch {}
  }, 600);
}

function restoreSavedDraft() {
  try {
    const savedBody = localStorage.getItem(CONFIG.draftBodyKey);
    const savedTitle = localStorage.getItem(CONFIG.draftTitleKey);
    const savedFolder = localStorage.getItem(CONFIG.draftFolderKey);
    if (savedBody) elements.bodyInput.value = savedBody;
    if (savedTitle) elements.titleInput.value = savedTitle;
    if (savedFolder) elements.folderInput.value = savedFolder;
    if (savedBody || savedTitle || savedFolder) elements.draftTag.classList.add("visible");
  } catch {}
}

function clearSavedDraft() {
  try {
    localStorage.removeItem(CONFIG.draftBodyKey);
    localStorage.removeItem(CONFIG.draftTitleKey);
    localStorage.removeItem(CONFIG.draftFolderKey);
  } catch {}
  elements.draftTag.classList.remove("visible");
}

async function checkAuth() {
  elements.authStatusLoading.classList.remove("hidden");
  elements.authStatusSignedIn.classList.add("hidden");
  elements.authStatusSignedOut.classList.add("hidden");

  try {
    const response = await fetch(`${CONFIG.apiBase}/auth/status`, { credentials: "include" });
    const data = await response.json();
    state.isAuthenticated = data.authenticated;
    state.user = data.user || null;

    elements.authStatusLoading.classList.add("hidden");
    if (state.isAuthenticated) {
      elements.userLogin.textContent = state.user.login;
      elements.userAvatar.src = state.user.avatar_url;
      elements.authStatusSignedIn.classList.remove("hidden");
      fetchNotes();
    } else {
      elements.authStatusSignedOut.classList.remove("hidden");
    }
  } catch {
    elements.authStatusLoading.textContent = "Backend offline.";
  }
}

async function loginWithGitHub() {
  window.location.href = `${CONFIG.apiBase}/auth/login`;
}

async function logout() {
  try {
    await fetch(`${CONFIG.apiBase}/auth/logout`, { method: "POST", credentials: "include" });
    window.location.reload();
  } catch {
    setStatus("error", "Logout failed.");
  }
}

function loadFolderHistory() {
  try {
    const data = localStorage.getItem(CONFIG.folderHistoryKey);
    if (data) {
      state.folderHistory = JSON.parse(data);
    }
  } catch {}
  renderFolderChips();
}

function saveFolderHistory(folder) {
  if (!folder || isExcludedPath(folder) || state.privateMode) return;
  state.folderHistory = state.folderHistory.filter(f => f !== folder);
  state.folderHistory.unshift(folder);
  if (state.folderHistory.length > 5) state.folderHistory.pop();
  try {
    localStorage.setItem(CONFIG.folderHistoryKey, JSON.stringify(state.folderHistory));
  } catch {}
  renderFolderChips();
}

function renderFolderChips() {
  if (state.folderHistory.length === 0) {
    elements.folderChips.innerHTML = '';
    return;
  }
  elements.folderChips.innerHTML = state.folderHistory.map(folder => {
    return `<button type="button" class="folder-chip" data-folder="${escapeHtml(folder)}">${escapeHtml(folder)}</button>`;
  }).join('');
}

function updateFolderIndex(tree) {
  const folders = new Set();
  const stats = {};
  tree.forEach(entry => {
    if (entry.type === 'blob' && entry.path.startsWith(CONFIG.vaultPrefix) && !isExcludedPath(entry.path)) {
      const parts = entry.path.replace(CONFIG.vaultPrefix, '').split('/');
      parts.pop(); 
      let current = '';
      parts.forEach(part => {
        current = current ? `${current}/${part}` : part;
        folders.add(current);
        stats[current] = (stats[current] || 0) + 1;
      });
    }
  });
  state.folderIndex = Array.from(folders).sort((a, b) => (stats[b] || 0) - (stats[a] || 0));
  renderFolderSuggestions();
}

function renderFolderSuggestions() {
  const skip = ['index', 'notes'];
  elements.folderDatalist.innerHTML = state.folderIndex.map(path => {
    const parts = path.split('/');
    const terminal = parts[parts.length - 1];
    const label = skip.includes(terminal.toLowerCase()) && parts.length > 1
      ? `${parts[parts.length - 2]}/${terminal}`
      : terminal;
    return `<option value="${escapeHtml(path)}">${escapeHtml(label)}</option>`;
  }).join('');
}

function updateFolderHint() {
  const value = elements.folderInput.value.trim().replace(/^\/+|\/+$/g, '');
  if (!value || state.folderIndex.includes(value)) {
    elements.folderHint.classList.add('hidden');
  } else {
    elements.folderHint.textContent = `New folder: ${value}`;
    elements.folderHint.classList.remove('hidden');
  }
}

function renderPreview() {
  const title = elements.titleInput.value.trim();
  const body = elements.bodyInput.value;
  elements.previewTitle.textContent = title;
  elements.previewTitle.classList.toggle("hidden", !title);

  if (!body.trim()) {
    elements.previewBody.innerHTML = '<p class="preview-empty">Nothing to preview yet</p>';
    return;
  }

  const html = marked.parse(body, { breaks: true, gfm: true });
  elements.previewBody.innerHTML = DOMPurify.sanitize(html);
  
  if (window.MathJax) {
    MathJax.typesetPromise([elements.previewBody]).catch(() => {});
  }
}

function setEditorMode(mode) {
  const showPreview = mode === "preview";
  elements.writeTab.classList.toggle("active", !showPreview);
  elements.previewTab.classList.toggle("active", showPreview);
  elements.writePane.classList.toggle("active", !showPreview);
  elements.previewPane.classList.toggle("active", showPreview);
}

function clearDeleteConfirmation() {
  state.confirmDeletePath = null;
  if (state.deleteConfirmTimer) {
    clearTimeout(state.deleteConfirmTimer);
    state.deleteConfirmTimer = null;
  }
}

function armDeleteConfirmation(path) {
  clearDeleteConfirmation();
  state.confirmDeletePath = path;
  state.deleteConfirmTimer = setTimeout(() => {
    clearDeleteConfirmation();
    renderNoteList();
  }, CONFIG.deleteConfirmMs);
}

function setMutationState(isMutating) {
  state.isMutating = isMutating;
  elements.uploadBtn.disabled = isMutating;
  elements.cancelEditBtn.disabled = isMutating;
  renderNoteList();
}

function filteredNotes() {
  const query = state.searchQuery.trim();
  if (!query) return state.notes;
  if (!fuseIndex) {
    const qLower = query.toLowerCase();
    return state.notes.filter((note) => note.path.toLowerCase().includes(qLower));
  }
  const results = fuseIndex.search(query);
  return results.map(result => ({ ...result.item, matches: result.matches }));
}

function renderNoteList() {
  if (state.listStatus === "loading") {
    elements.noteList.innerHTML = '<p class="list-state">Scanning vault notes…</p>';
    elements.noteCount.textContent = "Syncing";
    return;
  }

  if (state.listStatus === "error") {
    elements.noteList.innerHTML = `<p class="list-state">${escapeHtml(state.listError || "Unable to load notes from GitHub.")}</p>`;
    elements.noteCount.textContent = "Error";
    return;
  }

  const notes = filteredNotes();
  if (notes.length === 0) {
    const message = state.isAuthenticated
      ? (state.searchQuery ? `No matches for "${escapeHtml(state.searchQuery)}".` : "No notes found in vault. Your new notes will appear here.")
      : "Please sign in with GitHub to manage your vault notes.";
    elements.noteList.innerHTML = `<p class="list-state">${message}</p>`;
    elements.noteCount.textContent = "0 files";
    return;
  }

  elements.noteCount.textContent = `${notes.length} files`;
  elements.noteList.innerHTML = notes.map((note) => {
    const confirmDelete = state.confirmDeletePath === note.path;
    const deleteLabel = confirmDelete ? "Confirm Delete" : "Delete";
    const titleHtml = highlightMatch(note.displayPath, note.matches, 'displayPath');
    
    return `
      <article class="vault-card">
        <div class="vault-card__top">
          <div class="vault-card__content">
            <h3 class="vault-card__title">${titleHtml}</h3>
          </div>
        </div>
        <div class="vault-actions">
          <button class="action-btn" type="button" data-action="edit" data-path="${escapeHtml(note.path)}" ${state.isMutating || !state.isAuthenticated ? "disabled" : ""}>Edit</button>
          <button class="action-btn danger ${confirmDelete ? "active-danger" : ""}" type="button" data-action="delete" data-path="${escapeHtml(note.path)}" data-sha="${escapeHtml(note.sha || "")}" ${state.isMutating || !state.isAuthenticated ? "disabled" : ""}>${escapeHtml(deleteLabel)}</button>
        </div>
      </article>
    `;
  }).join("");
}

function updateModeUi() {
  const editing = state.mode === "edit";
  elements.uploadBtn.textContent = editing ? "Update Note" : "Save to Vault";
  elements.cancelEditBtn.classList.toggle("hidden", !editing);
  elements.folderInput.disabled = editing;
}

function restoreDraftSnapshot() {
  if (!state.draftSnapshot) return;
  elements.titleInput.value = state.draftSnapshot.title;
  elements.bodyInput.value = state.draftSnapshot.body;
  elements.folderInput.value = state.draftSnapshot.folder || "";
  state.draftSnapshot = null;
  saveDraftSoon();
  renderPreview();
}

function enterCreateMode() {
  state.mode = "create";
  state.editingPath = null;
  state.editingSha = null;
  state.titleLocked = false;
  state.autoGeneratedTitle = "";
  
  const lastFolder = sessionStorage.getItem(CONFIG.lastFolderKey);
  if (lastFolder && !elements.folderInput.value) {
    elements.folderInput.value = lastFolder;
  }
  
  updateModeUi();
  updateFolderHint();
}

function exitEditMode({ restoreDraft = true } = {}) {
  enterCreateMode();
  if (restoreDraft) {
    restoreDraftSnapshot();
  } else {
    state.draftSnapshot = null;
  }
}

async function apiRequest(endpoint, options = {}) {
  const url = `${CONFIG.apiBase}${endpoint}`;
  options.credentials = "include";

  const response = await fetch(url, options);
  if (response.status === 401) {
    state.isAuthenticated = false;
    checkAuth();
    throw new Error("Unauthorized. Please sign in again.");
  }
  
  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({}));
    throw new Error(errorBody.detail || errorBody.message || `Request failed: ${response.status}`);
  }
  return response.json();
}

async function getFileContent(path) {
  return await apiRequest(`/api/vault/content/${path}`);
}

export async function putFile(path, content, sha, message) {
  const base64Content = btoa(content instanceof Uint8Array 
    ? Array.from(content, b => String.fromCharCode(b)).join('') 
    : Array.from(new TextEncoder().encode(content), b => String.fromCharCode(b)).join(''));

  return apiRequest("/api/vault/save", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ path, content: base64Content, sha, message })
  });
}

async function deleteFile(path, sha, message) {
  return apiRequest("/api/vault/delete", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ path, sha, message })
  });
}

async function fetchNotes() {
  if (!state.isAuthenticated) return;
  state.listStatus = "loading";
  state.listError = "";
  clearDeleteConfirmation();
  renderNoteList();

  try {
    const data = await apiRequest("/api/vault/notes");
    const tree = data.tree || [];
    updateFolderIndex(tree);

    const files = tree
      .filter((entry) => entry.type === "blob" && isVaultPathSafe(entry.path))
      .sort((a, b) => b.path.localeCompare(a.path));

    state.notes = files.map((entry) => ({
      path: entry.path,
      displayPath: entry.path.replace(/^vault\//, ''),
      title: noteStemFromPath(entry.path),
      sha: entry.sha || null,
    }));

    updateFuseIndex();
    state.listStatus = "ready";
    renderNoteList();
  } catch (error) {
    state.listStatus = "error";
    state.listError = error.message || "Unable to load notes.";
    renderNoteList();
  }
}

async function startEditing(path) {
  if (state.isMutating) return;
  if (!state.isAuthenticated) {
    setStatus("error", "Please sign in to edit notes.");
    return;
  }

  clearDeleteConfirmation();
  setMutationState(true);
  setStatus("uploading", "Loading note…");

  try {
    if (!state.draftSnapshot) {
      state.draftSnapshot = {
        title: elements.titleInput.value,
        body: elements.bodyInput.value,
        folder: elements.folderInput.value,
      };
    }

    const data = await getFileContent(path);
    const binary = atob((data.content || "").replace(/\s/g, ""));
    const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
    const content = new TextDecoder().decode(bytes);
    const parsed = parseEditableNote(path, content);
    
    const displayPath = path.replace(/^vault\//, '');
    const lastSlash = displayPath.lastIndexOf('/');
    const folder = lastSlash > -1 ? displayPath.substring(0, lastSlash) : '';
    
    elements.titleInput.value = parsed.title;
    elements.bodyInput.value = parsed.body;
    elements.folderInput.value = folder;
    state.mode = "edit";
    state.editingPath = path;
    state.editingSha = data.sha || null;
    state.titleLocked = true;
    updateModeUi();
    renderPreview();
    setStatus("success", "Editing vault note.");
  } catch (error) {
    setStatus("error", error.message || "Unable to load note.");
    if (state.mode !== "edit") state.draftSnapshot = null;
  } finally {
    setMutationState(false);
  }
}

async function handleDelete(path, shaHint) {
  if (!state.isAuthenticated) {
    setStatus("error", "Please sign in to delete notes.");
    return;
  }

  if (state.confirmDeletePath !== path) {
    armDeleteConfirmation(path);
    renderNoteList();
    setStatus("error", "Tap delete again to confirm.");
    return;
  }

  clearDeleteConfirmation();
  setMutationState(true);
  setStatus("uploading", "Deleting note…");

  try {
    const foundNote = state.notes.find((note) => note.path === path);
    const sha = shaHint || (foundNote ? foundNote.sha : null);
    if (!sha) throw new Error("Missing file SHA for delete.");
    await deleteFile(path, sha, `vault: delete ${path.split("/").pop()}`);
    if (state.editingPath === path) exitEditMode({ restoreDraft: true });
    await fetchNotes();
    setStatus("success", "Note deleted.");
  } catch (error) {
    setStatus("error", error.message || "Delete failed.");
  } finally {
    setMutationState(false);
  }
}

async function handleSave() {
  if (!state.isAuthenticated) {
    setStatus("error", "Please sign in to save notes.");
    return;
  }
  const title = elements.titleInput.value.trim();
  let folder = normalizeFolderPath(elements.folderInput.value);
  
  if (!folder && state.mode === "create") {
    const last = sessionStorage.getItem(CONFIG.lastFolderKey);
    if (last) {
      folder = last;
    } else {
      const now = new Date();
      const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
      folder = `Notes/${dateStr}`;
    }
  }

  const body = elements.bodyInput.value;
  if (!body.trim()) {
    setStatus("error", "Note is empty.");
    elements.bodyInput.focus();
    return;
  }

  clearDeleteConfirmation();
  setMutationState(true);
  setStatus("uploading", state.mode === "edit" ? "Updating vault note…" : "Saving to vault…");

  try {
    const filename = buildFilename(title);
    const fullPath = folder ? `${folder}/${filename}` : filename;
    const path = state.mode === "edit" ? state.editingPath : `${CONFIG.vaultPrefix}${fullPath}`;
    const fallbackTitle = noteStemFromPath(path);
    const message = state.mode === "edit"
      ? `vault: update ${path.split("/").pop()}`
      : `vault: add ${path.split("/").pop()}`;
    await putFile(path, buildMarkdown(title, body, fallbackTitle), state.mode === "edit" ? state.editingSha : null, message);
    await fetchNotes();
    
    if (!isExcludedPath(folder) && !state.privateMode) {
      saveFolderHistory(folder);
      sessionStorage.setItem(CONFIG.lastFolderKey, folder);
    }

    if (state.mode === "edit") {
      exitEditMode({ restoreDraft: true });
      setStatus("success", "Note updated.");
    } else {
      clearSavedDraft();
      elements.titleInput.value = "";
      elements.folderInput.value = "";
      elements.bodyInput.value = "";
      renderPreview();
      setStatus("success", `Uploaded ${path.split("/").pop()}. Site rebuilding (~60s)`);
    }
  } catch (error) {
    setStatus("error", error.message || "Save failed. Check token and network.");
  } finally {
    setMutationState(false);
  }
}

function togglePrivateMode() {
  state.privateMode = !state.privateMode;
  elements.privateModeToggle.textContent = state.privateMode ? "Private: ON" : "Private: OFF";
  elements.privateModeToggle.style.color = state.privateMode ? "var(--ink)" : "var(--ink-body)";
  elements.privateModeToggle.style.borderColor = state.privateMode ? "var(--ink)" : "var(--ink-ghost)";
  
  if (state.privateMode) {
    elements.folderInput.removeAttribute("list");
    elements.folderChips.classList.add("hidden");
    elements.folderHint.classList.add("hidden");
  } else {
    elements.folderInput.setAttribute("list", "folder-suggestions");
    elements.folderChips.classList.remove("hidden");
    updateFolderHint();
  }
}

function bindEvents() {
  elements.loginBtn.addEventListener("click", loginWithGitHub);
  elements.logoutBtn.addEventListener("click", logout);
  elements.privateModeToggle.addEventListener("click", togglePrivateMode);
  elements.folderInput.addEventListener("input", () => { 
    saveDraftSoon(); 
    updateFolderHint();
  });
  elements.folderChips.addEventListener("click", (e) => {
    const chip = e.target.closest(".folder-chip");
    if (!chip || state.mode === "edit") return;
    elements.folderInput.value = chip.dataset.folder;
    saveDraftSoon();
    updateFolderHint();
  });
  elements.titleInput.addEventListener("input", () => { 
    state.titleLocked = true;
    saveDraftSoon(); 
    renderPreview(); 
  });
  elements.bodyInput.addEventListener("input", () => { 
    if (!state.titleLocked && state.mode === "create") {
      const autoTitle = extractAutoTitle(elements.bodyInput.value);
      if (autoTitle !== state.autoGeneratedTitle) {
        state.autoGeneratedTitle = autoTitle;
        elements.titleInput.value = autoTitle;
      }
    }
    saveDraftSoon(); 
    renderPreview(); 
  });
  elements.writeTab.addEventListener("click", () => setEditorMode("write"));
  elements.previewTab.addEventListener("click", () => setEditorMode("preview"));
  elements.noteSearchInput.addEventListener("input", () => {
    state.searchQuery = elements.noteSearchInput.value;
    clearDeleteConfirmation();
    renderNoteList();
  });
  elements.noteList.addEventListener("click", async (event) => {
    const button = event.target.closest("[data-action]");
    if (!button || state.isMutating) return;
    const path = button.dataset.path;
    if (!isVaultPathSafe(path)) { setStatus("error", "Unsafe vault path rejected."); return; }
    if (button.dataset.action === "edit") { await startEditing(path); return; }
    if (button.dataset.action === "delete") { await handleDelete(path, button.dataset.sha || null); }
  });
  elements.cancelEditBtn.addEventListener("click", () => {
    if (state.isMutating) return;
    exitEditMode({ restoreDraft: true });
    setStatus("success", "Edit cancelled. Draft restored.");
  });
  elements.uploadBtn.addEventListener("click", handleSave);

  const attachBtn = document.getElementById("attach-btn");
  const cameraBtn = document.getElementById("camera-btn");
  if (attachBtn) {
    attachBtn.addEventListener("click", () => {
      triggerFilePicker(elements.bodyInput, () => state);
    });
  }
  if (cameraBtn) {
    cameraBtn.addEventListener("click", () => {
      triggerCameraCapture(elements.bodyInput, () => state);
    });
  }
}

function boot() {
  checkAuth();
  restoreSavedDraft();
  loadFolderHistory();
  bindEvents();
  setEditorMode("write");
  updateModeUi();
  renderPreview();
  renderNoteList();
}

boot();
